### ISSUE TITLE
ocamlformat cannot be found

### ISSUE THREAD

**Issue by PurePureMilk** [badochov/ocamlformatter-vscode#2]
![Annotation 2020-02-22 152318](https://user-images.githubusercontent.com/45339546/75098684-454f6b00-5587-11ea-96fc-0069ae4c9ac8.png)
Does "ocaml-formatter.profile" have to do with anything?

**Comment by badochov** [comment]
I don't think so it looks as if you didn't have ocamlformat installed

**Comment by PurePureMilk** [comment]
![Annotation 2020-02-23 111320](https://user-images.githubusercontent.com/45339546/75115558-9a45bc80-562d-11ea-8d43-82fe01174cb0.png)
![Annotation 2020-02-23 111309](https://user-images.githubusercontent.com/45339546/75115559-9b76e980-562d-11ea-98a3-d40fa917a382.png)
Bit strange. Looks like ocamlformat should already installed since I used opam install before.

**Comment by badochov** [comment]
Profile is not for path, but for ocamlformat profile, I see that you use wsl and I know that my extension doesn't work a lot of times in wsl

**Comment by hoddy3190** [comment]
I had the same issue `ocamlformat: not found`. I use OSX.

I forked this repository and I was able to solve the issue.
fixed commit: https://github.com/hoddy3190/ocamlformatter-vscode/commit/9c15d5d9012b86550338129e6dc790b9434c6a06

Almost all OCaml users use opam, but I think this problem can occur for those using [local switches](https://opam.ocaml.org/doc/Manual.html#Structure) (one of the function of opam). 

If we use local switches, `_opam` directory is created in our project, and install dependencies in it. It may be similar to `node_modules` directory.
But there is a big difference. Every time we move to the project directory, we have to run `eval $(opam env)` to refresh the environment (including pathes).

So (1) use local switches and (2) install ocamlformat only local (in _opam, not globally), the problem ocuurs.

There are some solutions.
1. Run `eval $(opam env)` every time before running commands related to OCaml.
    - My fix commit is this method, but it's rough especially error handling.
2. Add a configuration of VSCode to be able to select ocamlformat path.
3. Modify README to tell users need to install ocamlformat "in global" (~/.opam), not in local switches.

I hope this will help.

**Comment by badochov** [comment]
Thanks @hoddy3190 for shedding light on this issue, I'll add option to select ocamlformat path and modify README as you suggested.

**Comment by badochov** [comment]
@hoddy3190 @PurePureMilk I added option to chose ocamlformat path in version 1.1, hope it works for you!

**Comment by badochov** [comment]
I'll close this issue if fix doesn't work for you feel free to reopen it.

**Comment by badochov** [comment]
I've decided to add also option to run eval opam env before every call, deafult is that it doesn't run

**Comment by hoddy3190** [comment]
Thank you for your quick response and fix.
I tried eval-opam-env, but it didn't work.
I sent a pull request https://github.com/badochov/ocamlformatter-vscode/pull/6 to fix it.

**Comment by badochov** [comment]
Thank you for your contribution bug fix update is published!
