### ISSUE TITLE
Format error if code includes single quotations

### ISSUE THREAD

**Issue by hoddy3190** [badochov/ocamlformatter-vscode#7]
When I format code including single quotation, for example type variables, error always occurs. 

cause: https://github.com/badochov/ocamlformatter-vscode/blob/817084d60738e2f62c5def67b5dcd04f1b56348d/src/extension.ts#L30

e.g.
```
let sum: 'a -> 'b -> 'c = fun x y -> x + y;;
```
↓ sanitize
```
let sum: '\''a -> '\''b -> '\''c = fun x y -> x + y;;
```

**Comment by badochov** [comment]
Error occured while moving from printf to feeding the text directly by node, fixed
